sudo: required
language: python
cache: pip

services:
  - docker

python:
  - "3.6"

before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - sudo apt-get update -y && sudo apt-get install -y curl
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

install:
  - pip install mypy mypy-protobuf grpcio-tools grpcio

script:
  - make all -B
  # Try and build all the containers in docker-compose
  - sh deploy_to_docker_hub.sh

  # Try and test each microservice
#  - if [ "$AUTH" == 1 ]; then  mypy auth --strict; fi
