sudo: required
language: python
cache: pip

services:
  - docker

python:
  - "3.6"

env:
  - AUTH=1
  - COMPOSE=1

before_install:
  - sudo apt-get update -y && sudo apt-get install -y curl
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

install:
  - pip install mypy mypy-protobuf

script:
  # Try and build all the containers in docker-compose
  - if [ "$COMPOSE" == 1 ]; then docker-compose build; fi
  
  # Try and test each microservice
  - if [ "$AUTH" == 1 ]; then  mypy auth --strict; fi
