version: '3'
services:
  tester:
    build:
      context: tester
    tty: true
    links:
      - apilayer
      - auth
      - post_importer:post-importer
 
  web_client:
    build:
        context: web_client
    stdin_open: true
    tty: true
    links:
      - apilayer
    ports:
      - "80:80"

  client:
    build:
      context: client
    tty: true
    links:
      - apilayer

  create_user:
    build:
      context: create_user
    tty: true
    links:
      - users
    ports:
     - 3001
  
  users:
    build:
      context: users
    tty: true
    links:
            - users_db:usersdb
    ports:
      - 3002

  users_db:
    build:
      context: users_db 
    ports:
      - 3003

  apilayer:
    build:
      context: apilayer
    tty: true
    links:
      - auth
      - token_dispenser:token
      - post_importer:post-importer
      - news_feed:news-feed
      - wall
      - create_user:create-user
    expose:
      - 50051

  friends:
    build:
      context: friends
    tty: true
    links:
      - friends_postgres:friendsdb
    ports:
      - 2884
  friends_postgres:
    build:
      context: friends_db

  news_feed:
    build:
      context: news_feed
    tty: true
    ports:
      - 8080
    links:
      - news_feed_data_access:news-feed-data-access
      - posts

  posts:
    build:
      context: posts
    tty: true
    links:
      - posts_postgres:postsdb
      - posts_redis:posts-cache
    ports:
      - 2885
  posts_postgres:
    build:
      context: posts_db
# TODO: Integrate redis to posts
  posts_redis:
    image: redis:alpine

  profile:
    build:
      context: profile
    tty: true
    links:
      - profile_redis:profile-cache
    ports:
      - 2886
# TODO: Integrate redis to profile
  profile_redis:
    image: redis:alpine

  auth:
    build:
      context: auth
    tty: true
    links:
      - token_dispenser:token-dispenser
      - user_settings:user-setting
    ports:
      - 2884

  # Testing service
#  post_importer_cpp:
#    build:
#      context: post_importer_cpp
#    tty: true
#    links:
#      - post_importer_redis
#      - post_importer_kafka:kafka
#    ports:
#      - 9000
#    environment:
#      - IMPORT_QUEUE=post_import
#      - POST_INCREMENT_KEY=global_post_id
  post_importer:
    build:
      context: post_importer_cpp
    tty: true
    links:
      - post_importer_redis:post-importer-redis
#      - post_importer_kafka:post-importer-kafka
    ports:
      - 9000
    environment:
      - IMPORT_QUEUE=post_import
      - POST_INCREMENT_KEY=global_post_id
  post_importer_redis:
    image: redis:alpine
  post_importer_zookeeper:
    image: wurstmeister/zookeeper
    tty: true
    ports:
      - 2181
  post_importer_kafka:
    image: wurstmeister/kafka:latest
    ports:
      - 9094
    links:
      - post_importer_zookeeper:zookeeper
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  token_dispenser:
    build:
      context: token_dispenser
    tty: true
    links:
      - token_dispenser_redis:token-dispenser-redis
  token_dispenser_redis:
    image: redis:alpine

  news_feed_merge:
    build:
      context: news_feed_merge
    tty: true
    links:
      - news_feed_data_access:news-feed-data-access
      - friends
      - post_importer_redis:post-importer-redis
      - wall
      - posts
    environment:
      - IMPORT_QUEUE=post_import

  wall:
    build:
      context: wall
    tty: true
    links:
      - wall_redis:wall-cache
      - wall_postgres:walldb
      - posts
    ports:
      - 4698
  wall_redis:
    image: redis:alpine
  wall_postgres:
    build:
      context: wall_db

  news_feed_data_access:
    build: 
      context: news_feed_data_access
    tty: true
    links:
      - news_feed_data_access_redis:news-feed-data-access-redis
      - news_feed_data_access_postgres:news-feed-data-access-postgres
  news_feed_data_access_redis:
    image: redis:alpine
  news_feed_data_access_postgres:
    build:
      context: news_feed_data_access/db
    tty: true

  user_settings:
    build:
      context: user_setting
    tty: true
    links:
      - user_settings_postgres:usersettingdb
  user_settings_postgres:
    build:
      context: user_setting_db
