version: '3'
services:
  tester:
    build:
      context: tester
    tty: true
    links:
      - apilayer

  apilayer:
    build:
      context: apilayer
    tty: true
    links:
      - auth
      - token_dispenser:token
    expose:
      - 50051
    ports:
      - 50051

  auth:
    build:
      context: auth
    tty: true
    links:
      - token_dispenser

  post_importer:
    build:
      context: post_importer
    tty: true
    links:
      - post_importer_redis
  post_importer_redis:
    image: redis:alpine

  token_dispenser:
    build:
      context: token_dispenser
    tty: true
    links:
      - token_dispenser_redis
  token_dispenser_redis:
    image: redis:alpine

  news_feed_data_access:
    build: 
      context: news_feed_data_access
    tty: true
    links:
      - news_feed_data_access_redis
      - news_feed_data_access_postgres
  news_feed_data_access_redis:
    image: redis:alpine
  news_feed_data_access_postgres:
    image: postgres:alpine