version: '3'
services:
  tester:
    build:
      context: tester
    tty: true
    links:
      - apilayer
      - auth
      - post_importer:postImporter

  client:
    build:
      context: client
    tty: true
    links:
      - apilayer

  apilayer:
    build:
      context: apilayer
    tty: true
    links:
      - auth
      - token_dispenser:token
      - post_importer:postImporter
      - news_feed:newsFeed
      - wall
    expose:
      - 50051

  friends:
    build:
      context: friends
    tty: true
    links:
      - friends_postgres:friendsdb
    ports:
      - 2884
  friends_postgres:
    build:
      context: friends_db

  news_feed:
    build:
      context: news_feed
    tty: true
    ports:
      - 2884

  posts:
    build:
      context: posts
    tty: true
    links:
      - posts_postgres:postsdb
      - posts_redis:postsCache
    ports:
      - 2885
  posts_postgres:
    build:
      context: posts_db
  posts_redis:
    image: redis:alpine

  profile:
    build:
      context: profile
    tty: true
    links:
      - profile_redis:profileCache
    ports:
      - 2886
  profile_redis:
    image: redis:alpine

  auth:
    build:
      context: auth
    tty: true
    links:
      - token_dispenser:tokendispenser
      - user_settings:usersettings
    ports:
      - 2884

  post_importer:
    build:
      context: post_importer
    tty: true
    links:
      - post_importer_redis
    ports:
      - 9000
    environment:
      - IMPORT_QUEUE=post_import
      - POST_INCREMENT_KEY=global_post_id
  post_importer_redis:
    image: redis:alpine

  token_dispenser:
    build:
      context: token_dispenser
    tty: true
    links:
      - token_dispenser_redis
  token_dispenser_redis:
    image: redis:alpine

  news_feed_merge:
    build:
      context: news_feed_merge
    tty: true
    links:
      - news_feed_data_access:newsFeedDataAccess
      - friends
      - post_importer_redis
      - wall
      - posts
    environment:
      - IMPORT_QUEUE=post_import

  wall:
    build:
      context: wall
    tty: true
    links:
      - wall_redis:wallCache
      - wall_postgres:walldb
      - posts
    ports:
      - 4698
  wall_redis:
    image: redis:alpine
  wall_postgres:
    build:
      context: wall_db

  news_feed_data_access:
    build: 
      context: news_feed_data_access
    tty: true
    links:
      - news_feed_data_access_redis
      - news_feed_data_access_postgres
  news_feed_data_access_redis:
    image: redis:alpine
  news_feed_data_access_postgres:
    build:
      context: news_feed_data_access/db
    tty: true

  user_settings:
    build:
      context: user_setting
    tty: true
    links:
      - user_settings_postgres:usersettingdb
  user_settings_postgres:
    build:
      context: user_setting_db