version: '3'
services:
  tester:
    build:
      context: tester
    tty: true
    links:
      - apilayer
      - auth
      - post_importer:postImporter

  apilayer:
    build:
      context: apilayer
    tty: true
    links:
      - auth
      - token_dispenser:token
      - post_importer:postImporter
    expose:
      - 50051

  auth:
    build:
      context: auth
    tty: true
    links:
      - token_dispenser
      - user_settings
    expose:
      - 2884

  post_importer:
    build:
      context: post_importer
    tty: true
    links:
      - post_importer_redis
    ports:
      - 9000
    environment:
      - IMPORT_QUEUE=post_import
      - POST_INCREMENT_KEY=global_post_id
  post_importer_redis:
    image: redis:alpine

  token_dispenser:
    build:
      context: token_dispenser
    tty: true
    links:
      - token_dispenser_redis
  token_dispenser_redis:
    image: redis:alpine

  news_feed_data_access:
    build: 
      context: news_feed_data_access
    tty: true
    links:
      - news_feed_data_access_redis
      - news_feed_data_access_postgres
  news_feed_data_access_redis:
    image: redis:alpine
  news_feed_data_access_postgres:
    image: postgres:alpine

  user_settings:
    build:
      context: user_setting
    tty: true
    links:
      - user_settings_postgres

  user_settings_postgres:
    image: postgres:alpine