//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: friends.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

internal protocol Foobar_Friends_FriendsServiceget_friendsCall: ClientCallServerStreaming {
  /// Do not call this directly, call `receive()` in the protocol extension below instead.
  func _receive(timeout: DispatchTime) throws -> Foobar_Friends_Friend?
  /// Call this to wait for a result. Nonblocking.
  func receive(completion: @escaping (ResultOrRPCError<Foobar_Friends_Friend?>) -> Void) throws
}

internal extension Foobar_Friends_FriendsServiceget_friendsCall {
  /// Call this to wait for a result. Blocking.
  func receive(timeout: DispatchTime = .distantFuture) throws -> Foobar_Friends_Friend? { return try self._receive(timeout: timeout) }
}

fileprivate final class Foobar_Friends_FriendsServiceget_friendsCallBase: ClientCallServerStreamingBase<Foobar_User_User, Foobar_Friends_Friend>, Foobar_Friends_FriendsServiceget_friendsCall {
  override class var method: String { return "/foobar.friends.FriendsService/get_friends" }
}

internal protocol Foobar_Friends_FriendsServicetop_friendsCall: ClientCallServerStreaming {
  /// Do not call this directly, call `receive()` in the protocol extension below instead.
  func _receive(timeout: DispatchTime) throws -> Foobar_Friends_Friend?
  /// Call this to wait for a result. Nonblocking.
  func receive(completion: @escaping (ResultOrRPCError<Foobar_Friends_Friend?>) -> Void) throws
}

internal extension Foobar_Friends_FriendsServicetop_friendsCall {
  /// Call this to wait for a result. Blocking.
  func receive(timeout: DispatchTime = .distantFuture) throws -> Foobar_Friends_Friend? { return try self._receive(timeout: timeout) }
}

fileprivate final class Foobar_Friends_FriendsServicetop_friendsCallBase: ClientCallServerStreamingBase<Foobar_User_User, Foobar_Friends_Friend>, Foobar_Friends_FriendsServicetop_friendsCall {
  override class var method: String { return "/foobar.friends.FriendsService/top_friends" }
}


/// Instantiate Foobar_Friends_FriendsServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Foobar_Friends_FriendsServiceService: ServiceClient {
  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  func get_friends(_ request: Foobar_User_User, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Foobar_Friends_FriendsServiceget_friendsCall

  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  func top_friends(_ request: Foobar_User_User, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Foobar_Friends_FriendsServicetop_friendsCall

}

internal extension Foobar_Friends_FriendsServiceService {
  /// Asynchronous. Server-streaming.
  func get_friends(_ request: Foobar_User_User, completion: ((CallResult) -> Void)?) throws -> Foobar_Friends_FriendsServiceget_friendsCall {
    return try self.get_friends(request, metadata: self.metadata, completion: completion)
  }

  /// Asynchronous. Server-streaming.
  func top_friends(_ request: Foobar_User_User, completion: ((CallResult) -> Void)?) throws -> Foobar_Friends_FriendsServicetop_friendsCall {
    return try self.top_friends(request, metadata: self.metadata, completion: completion)
  }

}

internal final class Foobar_Friends_FriendsServiceServiceClient: ServiceClientBase, Foobar_Friends_FriendsServiceService {
  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  internal func get_friends(_ request: Foobar_User_User, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Foobar_Friends_FriendsServiceget_friendsCall {
    return try Foobar_Friends_FriendsServiceget_friendsCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  internal func top_friends(_ request: Foobar_User_User, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Foobar_Friends_FriendsServicetop_friendsCall {
    return try Foobar_Friends_FriendsServicetop_friendsCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
internal protocol Foobar_Friends_FriendsServiceProvider: ServiceProvider {
  func get_friends(request: Foobar_User_User, session: Foobar_Friends_FriendsServiceget_friendsSession) throws -> ServerStatus?
  func top_friends(request: Foobar_User_User, session: Foobar_Friends_FriendsServicetop_friendsSession) throws -> ServerStatus?
}

extension Foobar_Friends_FriendsServiceProvider {
  internal var serviceName: String { return "foobar.friends.FriendsService" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  internal func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/foobar.friends.FriendsService/get_friends":
      return try Foobar_Friends_FriendsServiceget_friendsSessionBase(
        handler: handler,
        providerBlock: { try self.get_friends(request: $0, session: $1 as! Foobar_Friends_FriendsServiceget_friendsSessionBase) })
          .run()
    case "/foobar.friends.FriendsService/top_friends":
      return try Foobar_Friends_FriendsServicetop_friendsSessionBase(
        handler: handler,
        providerBlock: { try self.top_friends(request: $0, session: $1 as! Foobar_Friends_FriendsServicetop_friendsSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

internal protocol Foobar_Friends_FriendsServiceget_friendsSession: ServerSessionServerStreaming {
  /// Send a message to the stream. Nonblocking.
  func send(_ message: Foobar_Friends_Friend, completion: @escaping (Error?) -> Void) throws
  /// Do not call this directly, call `send()` in the protocol extension below instead.
  func _send(_ message: Foobar_Friends_Friend, timeout: DispatchTime) throws

  /// Close the connection and send the status. Non-blocking.
  /// This method should be called if and only if your request handler returns a nil value instead of a server status;
  /// otherwise SwiftGRPC will take care of sending the status for you.
  func close(withStatus status: ServerStatus, completion: (() -> Void)?) throws
}

internal extension Foobar_Friends_FriendsServiceget_friendsSession {
  /// Send a message to the stream and wait for the send operation to finish. Blocking.
  func send(_ message: Foobar_Friends_Friend, timeout: DispatchTime = .distantFuture) throws { try self._send(message, timeout: timeout) }
}

fileprivate final class Foobar_Friends_FriendsServiceget_friendsSessionBase: ServerSessionServerStreamingBase<Foobar_User_User, Foobar_Friends_Friend>, Foobar_Friends_FriendsServiceget_friendsSession {}

internal protocol Foobar_Friends_FriendsServicetop_friendsSession: ServerSessionServerStreaming {
  /// Send a message to the stream. Nonblocking.
  func send(_ message: Foobar_Friends_Friend, completion: @escaping (Error?) -> Void) throws
  /// Do not call this directly, call `send()` in the protocol extension below instead.
  func _send(_ message: Foobar_Friends_Friend, timeout: DispatchTime) throws

  /// Close the connection and send the status. Non-blocking.
  /// This method should be called if and only if your request handler returns a nil value instead of a server status;
  /// otherwise SwiftGRPC will take care of sending the status for you.
  func close(withStatus status: ServerStatus, completion: (() -> Void)?) throws
}

internal extension Foobar_Friends_FriendsServicetop_friendsSession {
  /// Send a message to the stream and wait for the send operation to finish. Blocking.
  func send(_ message: Foobar_Friends_Friend, timeout: DispatchTime = .distantFuture) throws { try self._send(message, timeout: timeout) }
}

fileprivate final class Foobar_Friends_FriendsServicetop_friendsSessionBase: ServerSessionServerStreamingBase<Foobar_User_User, Foobar_Friends_Friend>, Foobar_Friends_FriendsServicetop_friendsSession {}

