//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: news_feed_data_access.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

internal protocol Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceget_news_feedCall: ClientCallServerStreaming {
  /// Do not call this directly, call `receive()` in the protocol extension below instead.
  func _receive(timeout: DispatchTime) throws -> Foobar_Posts_Post?
  /// Call this to wait for a result. Nonblocking.
  func receive(completion: @escaping (ResultOrRPCError<Foobar_Posts_Post?>) -> Void) throws
}

internal extension Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceget_news_feedCall {
  /// Call this to wait for a result. Blocking.
  func receive(timeout: DispatchTime = .distantFuture) throws -> Foobar_Posts_Post? { return try self._receive(timeout: timeout) }
}

fileprivate final class Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceget_news_feedCallBase: ClientCallServerStreamingBase<Foobar_Wall_WallQuery, Foobar_Posts_Post>, Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceget_news_feedCall {
  override class var method: String { return "/foobar.news_feed_data_access.NewsFeedDataAccessService/get_news_feed" }
}

internal protocol Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceadd_postCall: ClientCallUnary {}

fileprivate final class Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceadd_postCallBase: ClientCallUnaryBase<Foobar_NewsFeedDataAccess_NewsFeedPost, Foobar_Shared_Empty>, Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceadd_postCall {
  override class var method: String { return "/foobar.news_feed_data_access.NewsFeedDataAccessService/add_post" }
}


/// Instantiate Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceService: ServiceClient {
  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  func get_news_feed(_ request: Foobar_Wall_WallQuery, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceget_news_feedCall

  /// Synchronous. Unary.
  func add_post(_ request: Foobar_NewsFeedDataAccess_NewsFeedPost, metadata customMetadata: Metadata) throws -> Foobar_Shared_Empty
  /// Asynchronous. Unary.
  @discardableResult
  func add_post(_ request: Foobar_NewsFeedDataAccess_NewsFeedPost, metadata customMetadata: Metadata, completion: @escaping (Foobar_Shared_Empty?, CallResult) -> Void) throws -> Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceadd_postCall

}

internal extension Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceService {
  /// Asynchronous. Server-streaming.
  func get_news_feed(_ request: Foobar_Wall_WallQuery, completion: ((CallResult) -> Void)?) throws -> Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceget_news_feedCall {
    return try self.get_news_feed(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func add_post(_ request: Foobar_NewsFeedDataAccess_NewsFeedPost) throws -> Foobar_Shared_Empty {
    return try self.add_post(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func add_post(_ request: Foobar_NewsFeedDataAccess_NewsFeedPost, completion: @escaping (Foobar_Shared_Empty?, CallResult) -> Void) throws -> Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceadd_postCall {
    return try self.add_post(request, metadata: self.metadata, completion: completion)
  }

}

internal final class Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceServiceClient: ServiceClientBase, Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceService {
  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  internal func get_news_feed(_ request: Foobar_Wall_WallQuery, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceget_news_feedCall {
    return try Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceget_news_feedCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func add_post(_ request: Foobar_NewsFeedDataAccess_NewsFeedPost, metadata customMetadata: Metadata) throws -> Foobar_Shared_Empty {
    return try Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceadd_postCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func add_post(_ request: Foobar_NewsFeedDataAccess_NewsFeedPost, metadata customMetadata: Metadata, completion: @escaping (Foobar_Shared_Empty?, CallResult) -> Void) throws -> Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceadd_postCall {
    return try Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceadd_postCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
internal protocol Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceProvider: ServiceProvider {
  func get_news_feed(request: Foobar_Wall_WallQuery, session: Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceget_news_feedSession) throws -> ServerStatus?
  func add_post(request: Foobar_NewsFeedDataAccess_NewsFeedPost, session: Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceadd_postSession) throws -> Foobar_Shared_Empty
}

extension Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceProvider {
  internal var serviceName: String { return "foobar.news_feed_data_access.NewsFeedDataAccessService" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  internal func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/foobar.news_feed_data_access.NewsFeedDataAccessService/get_news_feed":
      return try Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceget_news_feedSessionBase(
        handler: handler,
        providerBlock: { try self.get_news_feed(request: $0, session: $1 as! Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceget_news_feedSessionBase) })
          .run()
    case "/foobar.news_feed_data_access.NewsFeedDataAccessService/add_post":
      return try Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceadd_postSessionBase(
        handler: handler,
        providerBlock: { try self.add_post(request: $0, session: $1 as! Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceadd_postSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

internal protocol Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceget_news_feedSession: ServerSessionServerStreaming {
  /// Send a message to the stream. Nonblocking.
  func send(_ message: Foobar_Posts_Post, completion: @escaping (Error?) -> Void) throws
  /// Do not call this directly, call `send()` in the protocol extension below instead.
  func _send(_ message: Foobar_Posts_Post, timeout: DispatchTime) throws

  /// Close the connection and send the status. Non-blocking.
  /// This method should be called if and only if your request handler returns a nil value instead of a server status;
  /// otherwise SwiftGRPC will take care of sending the status for you.
  func close(withStatus status: ServerStatus, completion: (() -> Void)?) throws
}

internal extension Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceget_news_feedSession {
  /// Send a message to the stream and wait for the send operation to finish. Blocking.
  func send(_ message: Foobar_Posts_Post, timeout: DispatchTime = .distantFuture) throws { try self._send(message, timeout: timeout) }
}

fileprivate final class Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceget_news_feedSessionBase: ServerSessionServerStreamingBase<Foobar_Wall_WallQuery, Foobar_Posts_Post>, Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceget_news_feedSession {}

internal protocol Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceadd_postSession: ServerSessionUnary {}

fileprivate final class Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceadd_postSessionBase: ServerSessionUnaryBase<Foobar_NewsFeedDataAccess_NewsFeedPost, Foobar_Shared_Empty>, Foobar_NewsFeedDataAccess_NewsFeedDataAccessServiceadd_postSession {}

