//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: profile.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

internal protocol Foobar_Profile_ProfileServiceget_userCall: ClientCallUnary {}

fileprivate final class Foobar_Profile_ProfileServiceget_userCallBase: ClientCallUnaryBase<Foobar_User_User, Foobar_User_UserInfo>, Foobar_Profile_ProfileServiceget_userCall {
  override class var method: String { return "/foobar.profile.ProfileService/get_user" }
}

internal protocol Foobar_Profile_ProfileServiceget_wallCall: ClientCallServerStreaming {
  /// Do not call this directly, call `receive()` in the protocol extension below instead.
  func _receive(timeout: DispatchTime) throws -> Foobar_Posts_Post?
  /// Call this to wait for a result. Nonblocking.
  func receive(completion: @escaping (ResultOrRPCError<Foobar_Posts_Post?>) -> Void) throws
}

internal extension Foobar_Profile_ProfileServiceget_wallCall {
  /// Call this to wait for a result. Blocking.
  func receive(timeout: DispatchTime = .distantFuture) throws -> Foobar_Posts_Post? { return try self._receive(timeout: timeout) }
}

fileprivate final class Foobar_Profile_ProfileServiceget_wallCallBase: ClientCallServerStreamingBase<Foobar_Wall_WallQuery, Foobar_Posts_Post>, Foobar_Profile_ProfileServiceget_wallCall {
  override class var method: String { return "/foobar.profile.ProfileService/get_wall" }
}


/// Instantiate Foobar_Profile_ProfileServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Foobar_Profile_ProfileServiceService: ServiceClient {
  /// Synchronous. Unary.
  func get_user(_ request: Foobar_User_User, metadata customMetadata: Metadata) throws -> Foobar_User_UserInfo
  /// Asynchronous. Unary.
  @discardableResult
  func get_user(_ request: Foobar_User_User, metadata customMetadata: Metadata, completion: @escaping (Foobar_User_UserInfo?, CallResult) -> Void) throws -> Foobar_Profile_ProfileServiceget_userCall

  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  func get_wall(_ request: Foobar_Wall_WallQuery, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Foobar_Profile_ProfileServiceget_wallCall

}

internal extension Foobar_Profile_ProfileServiceService {
  /// Synchronous. Unary.
  func get_user(_ request: Foobar_User_User) throws -> Foobar_User_UserInfo {
    return try self.get_user(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func get_user(_ request: Foobar_User_User, completion: @escaping (Foobar_User_UserInfo?, CallResult) -> Void) throws -> Foobar_Profile_ProfileServiceget_userCall {
    return try self.get_user(request, metadata: self.metadata, completion: completion)
  }

  /// Asynchronous. Server-streaming.
  func get_wall(_ request: Foobar_Wall_WallQuery, completion: ((CallResult) -> Void)?) throws -> Foobar_Profile_ProfileServiceget_wallCall {
    return try self.get_wall(request, metadata: self.metadata, completion: completion)
  }

}

internal final class Foobar_Profile_ProfileServiceServiceClient: ServiceClientBase, Foobar_Profile_ProfileServiceService {
  /// Synchronous. Unary.
  internal func get_user(_ request: Foobar_User_User, metadata customMetadata: Metadata) throws -> Foobar_User_UserInfo {
    return try Foobar_Profile_ProfileServiceget_userCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func get_user(_ request: Foobar_User_User, metadata customMetadata: Metadata, completion: @escaping (Foobar_User_UserInfo?, CallResult) -> Void) throws -> Foobar_Profile_ProfileServiceget_userCall {
    return try Foobar_Profile_ProfileServiceget_userCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  internal func get_wall(_ request: Foobar_Wall_WallQuery, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Foobar_Profile_ProfileServiceget_wallCall {
    return try Foobar_Profile_ProfileServiceget_wallCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
internal protocol Foobar_Profile_ProfileServiceProvider: ServiceProvider {
  func get_user(request: Foobar_User_User, session: Foobar_Profile_ProfileServiceget_userSession) throws -> Foobar_User_UserInfo
  func get_wall(request: Foobar_Wall_WallQuery, session: Foobar_Profile_ProfileServiceget_wallSession) throws -> ServerStatus?
}

extension Foobar_Profile_ProfileServiceProvider {
  internal var serviceName: String { return "foobar.profile.ProfileService" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  internal func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/foobar.profile.ProfileService/get_user":
      return try Foobar_Profile_ProfileServiceget_userSessionBase(
        handler: handler,
        providerBlock: { try self.get_user(request: $0, session: $1 as! Foobar_Profile_ProfileServiceget_userSessionBase) })
          .run()
    case "/foobar.profile.ProfileService/get_wall":
      return try Foobar_Profile_ProfileServiceget_wallSessionBase(
        handler: handler,
        providerBlock: { try self.get_wall(request: $0, session: $1 as! Foobar_Profile_ProfileServiceget_wallSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

internal protocol Foobar_Profile_ProfileServiceget_userSession: ServerSessionUnary {}

fileprivate final class Foobar_Profile_ProfileServiceget_userSessionBase: ServerSessionUnaryBase<Foobar_User_User, Foobar_User_UserInfo>, Foobar_Profile_ProfileServiceget_userSession {}

internal protocol Foobar_Profile_ProfileServiceget_wallSession: ServerSessionServerStreaming {
  /// Send a message to the stream. Nonblocking.
  func send(_ message: Foobar_Posts_Post, completion: @escaping (Error?) -> Void) throws
  /// Do not call this directly, call `send()` in the protocol extension below instead.
  func _send(_ message: Foobar_Posts_Post, timeout: DispatchTime) throws

  /// Close the connection and send the status. Non-blocking.
  /// This method should be called if and only if your request handler returns a nil value instead of a server status;
  /// otherwise SwiftGRPC will take care of sending the status for you.
  func close(withStatus status: ServerStatus, completion: (() -> Void)?) throws
}

internal extension Foobar_Profile_ProfileServiceget_wallSession {
  /// Send a message to the stream and wait for the send operation to finish. Blocking.
  func send(_ message: Foobar_Posts_Post, timeout: DispatchTime = .distantFuture) throws { try self._send(message, timeout: timeout) }
}

fileprivate final class Foobar_Profile_ProfileServiceget_wallSessionBase: ServerSessionServerStreamingBase<Foobar_Wall_WallQuery, Foobar_Posts_Post>, Foobar_Profile_ProfileServiceget_wallSession {}

