//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: post_importer.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

internal protocol Foobar_PostImporter_PostImporterServicecreate_postCall: ClientCallUnary {}

fileprivate final class Foobar_PostImporter_PostImporterServicecreate_postCallBase: ClientCallUnaryBase<Foobar_Posts_Post, Foobar_Shared_Empty>, Foobar_PostImporter_PostImporterServicecreate_postCall {
  override class var method: String { return "/foobar.post_importer.PostImporterService/create_post" }
}


/// Instantiate Foobar_PostImporter_PostImporterServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Foobar_PostImporter_PostImporterServiceService: ServiceClient {
  /// Synchronous. Unary.
  func create_post(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata) throws -> Foobar_Shared_Empty
  /// Asynchronous. Unary.
  @discardableResult
  func create_post(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata, completion: @escaping (Foobar_Shared_Empty?, CallResult) -> Void) throws -> Foobar_PostImporter_PostImporterServicecreate_postCall

}

internal extension Foobar_PostImporter_PostImporterServiceService {
  /// Synchronous. Unary.
  func create_post(_ request: Foobar_Posts_Post) throws -> Foobar_Shared_Empty {
    return try self.create_post(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func create_post(_ request: Foobar_Posts_Post, completion: @escaping (Foobar_Shared_Empty?, CallResult) -> Void) throws -> Foobar_PostImporter_PostImporterServicecreate_postCall {
    return try self.create_post(request, metadata: self.metadata, completion: completion)
  }

}

internal final class Foobar_PostImporter_PostImporterServiceServiceClient: ServiceClientBase, Foobar_PostImporter_PostImporterServiceService {
  /// Synchronous. Unary.
  internal func create_post(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata) throws -> Foobar_Shared_Empty {
    return try Foobar_PostImporter_PostImporterServicecreate_postCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func create_post(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata, completion: @escaping (Foobar_Shared_Empty?, CallResult) -> Void) throws -> Foobar_PostImporter_PostImporterServicecreate_postCall {
    return try Foobar_PostImporter_PostImporterServicecreate_postCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
internal protocol Foobar_PostImporter_PostImporterServiceProvider: ServiceProvider {
  func create_post(request: Foobar_Posts_Post, session: Foobar_PostImporter_PostImporterServicecreate_postSession) throws -> Foobar_Shared_Empty
}

extension Foobar_PostImporter_PostImporterServiceProvider {
  internal var serviceName: String { return "foobar.post_importer.PostImporterService" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  internal func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/foobar.post_importer.PostImporterService/create_post":
      return try Foobar_PostImporter_PostImporterServicecreate_postSessionBase(
        handler: handler,
        providerBlock: { try self.create_post(request: $0, session: $1 as! Foobar_PostImporter_PostImporterServicecreate_postSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

internal protocol Foobar_PostImporter_PostImporterServicecreate_postSession: ServerSessionUnary {}

fileprivate final class Foobar_PostImporter_PostImporterServicecreate_postSessionBase: ServerSessionUnaryBase<Foobar_Posts_Post, Foobar_Shared_Empty>, Foobar_PostImporter_PostImporterServicecreate_postSession {}

