//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: posts.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

internal protocol Foobar_Posts_PostServiceget_postsCall: ClientCallServerStreaming {
  /// Do not call this directly, call `receive()` in the protocol extension below instead.
  func _receive(timeout: DispatchTime) throws -> Foobar_Posts_Post?
  /// Call this to wait for a result. Nonblocking.
  func receive(completion: @escaping (ResultOrRPCError<Foobar_Posts_Post?>) -> Void) throws
}

internal extension Foobar_Posts_PostServiceget_postsCall {
  /// Call this to wait for a result. Blocking.
  func receive(timeout: DispatchTime = .distantFuture) throws -> Foobar_Posts_Post? { return try self._receive(timeout: timeout) }
}

fileprivate final class Foobar_Posts_PostServiceget_postsCallBase: ClientCallServerStreamingBase<Foobar_Posts_PostQuery, Foobar_Posts_Post>, Foobar_Posts_PostServiceget_postsCall {
  override class var method: String { return "/foobar.posts.PostService/get_posts" }
}

internal protocol Foobar_Posts_PostServicefetchCall: ClientCallUnary {}

fileprivate final class Foobar_Posts_PostServicefetchCallBase: ClientCallUnaryBase<Foobar_Posts_Post, Foobar_Posts_Post>, Foobar_Posts_PostServicefetchCall {
  override class var method: String { return "/foobar.posts.PostService/fetch" }
}

internal protocol Foobar_Posts_PostServicecreate_postCall: ClientCallUnary {}

fileprivate final class Foobar_Posts_PostServicecreate_postCallBase: ClientCallUnaryBase<Foobar_Posts_Post, Foobar_Shared_Empty>, Foobar_Posts_PostServicecreate_postCall {
  override class var method: String { return "/foobar.posts.PostService/create_post" }
}


/// Instantiate Foobar_Posts_PostServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Foobar_Posts_PostServiceService: ServiceClient {
  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  func get_posts(_ request: Foobar_Posts_PostQuery, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Foobar_Posts_PostServiceget_postsCall

  /// Synchronous. Unary.
  func fetch(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata) throws -> Foobar_Posts_Post
  /// Asynchronous. Unary.
  @discardableResult
  func fetch(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata, completion: @escaping (Foobar_Posts_Post?, CallResult) -> Void) throws -> Foobar_Posts_PostServicefetchCall

  /// Synchronous. Unary.
  func create_post(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata) throws -> Foobar_Shared_Empty
  /// Asynchronous. Unary.
  @discardableResult
  func create_post(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata, completion: @escaping (Foobar_Shared_Empty?, CallResult) -> Void) throws -> Foobar_Posts_PostServicecreate_postCall

}

internal extension Foobar_Posts_PostServiceService {
  /// Asynchronous. Server-streaming.
  func get_posts(_ request: Foobar_Posts_PostQuery, completion: ((CallResult) -> Void)?) throws -> Foobar_Posts_PostServiceget_postsCall {
    return try self.get_posts(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func fetch(_ request: Foobar_Posts_Post) throws -> Foobar_Posts_Post {
    return try self.fetch(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func fetch(_ request: Foobar_Posts_Post, completion: @escaping (Foobar_Posts_Post?, CallResult) -> Void) throws -> Foobar_Posts_PostServicefetchCall {
    return try self.fetch(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func create_post(_ request: Foobar_Posts_Post) throws -> Foobar_Shared_Empty {
    return try self.create_post(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func create_post(_ request: Foobar_Posts_Post, completion: @escaping (Foobar_Shared_Empty?, CallResult) -> Void) throws -> Foobar_Posts_PostServicecreate_postCall {
    return try self.create_post(request, metadata: self.metadata, completion: completion)
  }

}

internal final class Foobar_Posts_PostServiceServiceClient: ServiceClientBase, Foobar_Posts_PostServiceService {
  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  internal func get_posts(_ request: Foobar_Posts_PostQuery, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Foobar_Posts_PostServiceget_postsCall {
    return try Foobar_Posts_PostServiceget_postsCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func fetch(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata) throws -> Foobar_Posts_Post {
    return try Foobar_Posts_PostServicefetchCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func fetch(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata, completion: @escaping (Foobar_Posts_Post?, CallResult) -> Void) throws -> Foobar_Posts_PostServicefetchCall {
    return try Foobar_Posts_PostServicefetchCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func create_post(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata) throws -> Foobar_Shared_Empty {
    return try Foobar_Posts_PostServicecreate_postCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func create_post(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata, completion: @escaping (Foobar_Shared_Empty?, CallResult) -> Void) throws -> Foobar_Posts_PostServicecreate_postCall {
    return try Foobar_Posts_PostServicecreate_postCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
internal protocol Foobar_Posts_PostServiceProvider: ServiceProvider {
  func get_posts(request: Foobar_Posts_PostQuery, session: Foobar_Posts_PostServiceget_postsSession) throws -> ServerStatus?
  func fetch(request: Foobar_Posts_Post, session: Foobar_Posts_PostServicefetchSession) throws -> Foobar_Posts_Post
  func create_post(request: Foobar_Posts_Post, session: Foobar_Posts_PostServicecreate_postSession) throws -> Foobar_Shared_Empty
}

extension Foobar_Posts_PostServiceProvider {
  internal var serviceName: String { return "foobar.posts.PostService" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  internal func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/foobar.posts.PostService/get_posts":
      return try Foobar_Posts_PostServiceget_postsSessionBase(
        handler: handler,
        providerBlock: { try self.get_posts(request: $0, session: $1 as! Foobar_Posts_PostServiceget_postsSessionBase) })
          .run()
    case "/foobar.posts.PostService/fetch":
      return try Foobar_Posts_PostServicefetchSessionBase(
        handler: handler,
        providerBlock: { try self.fetch(request: $0, session: $1 as! Foobar_Posts_PostServicefetchSessionBase) })
          .run()
    case "/foobar.posts.PostService/create_post":
      return try Foobar_Posts_PostServicecreate_postSessionBase(
        handler: handler,
        providerBlock: { try self.create_post(request: $0, session: $1 as! Foobar_Posts_PostServicecreate_postSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

internal protocol Foobar_Posts_PostServiceget_postsSession: ServerSessionServerStreaming {
  /// Send a message to the stream. Nonblocking.
  func send(_ message: Foobar_Posts_Post, completion: @escaping (Error?) -> Void) throws
  /// Do not call this directly, call `send()` in the protocol extension below instead.
  func _send(_ message: Foobar_Posts_Post, timeout: DispatchTime) throws

  /// Close the connection and send the status. Non-blocking.
  /// This method should be called if and only if your request handler returns a nil value instead of a server status;
  /// otherwise SwiftGRPC will take care of sending the status for you.
  func close(withStatus status: ServerStatus, completion: (() -> Void)?) throws
}

internal extension Foobar_Posts_PostServiceget_postsSession {
  /// Send a message to the stream and wait for the send operation to finish. Blocking.
  func send(_ message: Foobar_Posts_Post, timeout: DispatchTime = .distantFuture) throws { try self._send(message, timeout: timeout) }
}

fileprivate final class Foobar_Posts_PostServiceget_postsSessionBase: ServerSessionServerStreamingBase<Foobar_Posts_PostQuery, Foobar_Posts_Post>, Foobar_Posts_PostServiceget_postsSession {}

internal protocol Foobar_Posts_PostServicefetchSession: ServerSessionUnary {}

fileprivate final class Foobar_Posts_PostServicefetchSessionBase: ServerSessionUnaryBase<Foobar_Posts_Post, Foobar_Posts_Post>, Foobar_Posts_PostServicefetchSession {}

internal protocol Foobar_Posts_PostServicecreate_postSession: ServerSessionUnary {}

fileprivate final class Foobar_Posts_PostServicecreate_postSessionBase: ServerSessionUnaryBase<Foobar_Posts_Post, Foobar_Shared_Empty>, Foobar_Posts_PostServicecreate_postSession {}

