<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: posts.proto

namespace Foobar\Posts;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>foobar.posts.PostQuery</code>
 */
class PostQuery extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string username = 1;</code>
     */
    private $username = '';
    /**
     * Generated from protobuf field <code>int64 starting_id = 2;</code>
     */
    private $starting_id = 0;
    /**
     * Generated from protobuf field <code>int64 limit = 3;</code>
     */
    private $limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $username
     *     @type int|string $starting_id
     *     @type int|string $limit
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Posts::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string username = 1;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 starting_id = 2;</code>
     * @return int|string
     */
    public function getStartingId()
    {
        return $this->starting_id;
    }

    /**
     * Generated from protobuf field <code>int64 starting_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartingId($var)
    {
        GPBUtil::checkInt64($var);
        $this->starting_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 limit = 3;</code>
     * @return int|string
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>int64 limit = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt64($var);
        $this->limit = $var;

        return $this;
    }

}

