<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: posts.proto

namespace Foobar\Posts;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>foobar.posts.Post</code>
 */
class Post extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>string username = 2;</code>
     */
    private $username = '';
    /**
     * Generated from protobuf field <code>string msg = 3;</code>
     */
    private $msg = '';
    /**
     * Generated from protobuf field <code>int64 datetime = 4;</code>
     */
    private $datetime = 0;
    /**
     * Generated from protobuf field <code>.foobar.shared.Location loc = 5;</code>
     */
    private $loc = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $username
     *     @type string $msg
     *     @type int|string $datetime
     *     @type \Foobar\Shared\Location $loc
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Posts::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg = 3;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>string msg = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 datetime = 4;</code>
     * @return int|string
     */
    public function getDatetime()
    {
        return $this->datetime;
    }

    /**
     * Generated from protobuf field <code>int64 datetime = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDatetime($var)
    {
        GPBUtil::checkInt64($var);
        $this->datetime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.foobar.shared.Location loc = 5;</code>
     * @return \Foobar\Shared\Location
     */
    public function getLoc()
    {
        return $this->loc;
    }

    /**
     * Generated from protobuf field <code>.foobar.shared.Location loc = 5;</code>
     * @param \Foobar\Shared\Location $var
     * @return $this
     */
    public function setLoc($var)
    {
        GPBUtil::checkMessage($var, \Foobar\Shared\Location::class);
        $this->loc = $var;

        return $this;
    }

}

