# Profile Service
---
apiVersion: v1
kind: Service
metadata:
  name: profile
spec:
  ports:
    - port: 2885
  selector:
    app: profile
  type: ClusterIP

# Profile Deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: profile
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: mattpaletta/foobar-social_profile:latest
          imagePullPolicy: Always
          tty: True
          ports:
            - containerPort: 2885
          resources:
            requests:
              cpu: "500m"
              memory: "64Mi"
            limits:
              cpu: "800m"
              memory: "128Mi"