<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apilayer.proto

namespace GPBMetadata;

class Apilayer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Auth::initOnce();
        \GPBMetadata\Posts::initOnce();
        \GPBMetadata\NewsFeed::initOnce();
        \GPBMetadata\Wall::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae7020a0e6170696c617965722e70726f746f120f666f6f6261722e6170" .
            "696c617965721a0b706f7374732e70726f746f1a0f6e6577735f66656564" .
            "2e70726f746f1a0a77616c6c2e70726f746f32f2010a0f4170694c617965" .
            "725365727669636512300a056c6f67696e12112e666f6f6261722e617574" .
            "682e417574681a122e666f6f6261722e617574682e546f6b656e22001230" .
            "0a04706f737412122e666f6f6261722e706f7374732e506f73741a122e66" .
            "6f6f6261722e706f7374732e506f73742200123a0a086765745f77616c6c" .
            "12162e666f6f6261722e77616c6c2e57616c6c51756572791a122e666f6f" .
            "6261722e706f7374732e506f737422003001123f0a0d6765745f6e657773" .
            "5f6665656412162e666f6f6261722e77616c6c2e57616c6c51756572791a" .
            "122e666f6f6261722e706f7374732e506f737422003001421d0a0f666f6f" .
            "6261722e6170696c6179657242084170694c617965725001620670726f74" .
            "6f33"
        ), true);

        static::$is_initialized = true;
    }
}

