<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace GPBMetadata;

class Auth
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ade010a0a617574682e70726f746f120b666f6f6261722e61757468222a" .
            "0a044175746812100a08757365726e616d6518012001280912100a087061" .
            "7373776f726418022001280922280a05546f6b656e12100a08757365726e" .
            "616d65180120012809120d0a05746f6b656e18022001280932440a0b4175" .
            "74685365727669636512350a0a636865636b5f6175746812112e666f6f62" .
            "61722e617574682e417574681a122e666f6f6261722e617574682e546f6b" .
            "656e2200421f0a0b666f6f6261722e61757468420e41757468656e746963" .
            "6174696f6e5001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

