<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared.proto

namespace GPBMetadata;

class Shared
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a700a0c7368617265642e70726f746f120d666f6f6261722e7368617265" .
            "6422070a05456d70747922250a084c6f636174696f6e120b0a036c617418" .
            "0120012802120c0a046c6f6e6718022001280242190a0d666f6f6261722e" .
            "73686172656442065368617265645001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

