<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a620a0a757365722e70726f746f120b666f6f6261722e7573657222180a" .
            "045573657212100a08757365726e616d65180120012809220a0a08557365" .
            "72496e666f42190a0b666f6f6261722e7573657242085573657244617461" .
            "5001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

