<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wall.proto

namespace GPBMetadata;

class Wall
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Shared::initOnce();
        \GPBMetadata\User::initOnce();
        \GPBMetadata\Posts::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8f020a0a77616c6c2e70726f746f120b666f6f6261722e77616c6c1a0a" .
            "757365722e70726f746f1a0b706f7374732e70726f746f22410a0957616c" .
            "6c517565727912100a08757365726e616d6518012001280912130a0b7374" .
            "617274696e675f6964180220012803120d0a056c696d6974180320012803" .
            "32790a0b57616c6c5365727669636512370a05666574636812162e666f6f" .
            "6261722e77616c6c2e57616c6c51756572791a122e666f6f6261722e706f" .
            "7374732e506f73742200300112310a0370757412122e666f6f6261722e70" .
            "6f7374732e506f73741a142e666f6f6261722e7368617265642e456d7074" .
            "79220042150a0b666f6f6261722e77616c6c420457616c6c500162067072" .
            "6f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

