#Create User Service
---
apiVersion: v1
kind: Service
metadata:
  name: create-user
spec:
  ports:
    - port: 4477
  selector:
    app: create_user
  type: ClusterIP

#Create User Deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: create-user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: create_user
    spec:
      containers:
      - name: createuser
        image: mattpaletta/foobar-social_create_user:latest
        imagePullPolicy: Always
        tty: True
        ports:
          - containerPort: 4477
        resources:
          requests:
            cpu: "500m"
            memory: "64Mi"
          limits:
            cpu: "800m"
            memory: "128Mi"

