#Friends Service
---
apiVersion: v1
kind: Service
metadata:
  name: friends
spec:
  ports:
    - port: 2885
  selector:
    app: friends_service
  type: ClusterIP

#Friends Deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: friends
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: friends_service
    spec:
      containers:
        - name: friends
          image: mattpaletta/foobar-social_friends:latest
          imagePullPolicy: Always
          tty: True
          ports:
            - containerPort: 2885
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"

