# Api Layer Deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-layer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apilayer
    spec:
      containers:
        - name: apilayer
          image: mattpaletta/foobar-social_apilayer:latest
          imagePullPolicy: Always
          tty: True
          ports:
            - containerPort: 50051
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "800m"
              memory: "256Mi"

# Api Layer Service
---
apiVersion: v1
kind: Service
metadata:
  name: api-layer
spec:
  ports:
    - port: 50051
  selector:
    app: apilayer
  type: LoadBalancer