# News Feed Data Access Service
---
apiVersion: v1
kind: Service
metadata:
  name: news-feed-data-access
spec:
  ports:
    - port: 9000
  selector:
    app: news_feed_data_access
  type: ClusterIP

# News Feed Data Access Deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: news-feed-data-access
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: news_feed_data_access
    spec:
      containers:
        - name: newsfeeddataaccess
          image: mattpaletta/foobar-social_news_feed_data_access:latest
          imagePullPolicy: Always
          tty: True
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: "500m"
              memory: "64Mi"
            limits:
              cpu: "800m"
              memory: "128Mi"


# News Feed Data Access Postgres Service
---
apiVersion: v1
kind: Service
metadata:
  name: news-feed-data-access-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: news_feed_data_access_postgres
  type: ClusterIP

# News Feed Data Access Postgres Deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: news-feed-data-access-postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: news_feed_data_access_postgres
    spec:
      containers:
        - name: newsfeeddataaccesspostgres
          image: mattpaletta/foobar-social_news_feed_data_access_postgres:latest
          imagePullPolicy: Always
          tty: True
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "500m"
              memory: "64Mi"
            limits:
              cpu: "800m"
              memory: "128Mi"

# News Feed Data Access Redis Deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: news-feed-data-access-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: news_feed_data_access_redis
    spec:
      containers:
        - name: newsfeeddataaccessredis
          image: redis:alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "800m"
              memory: "512Mi"

# News Feed Data Access Redis Service
---
apiVersion: v1
kind: Service
metadata:
  name: news-feed-data-access-redis
spec:
  ports:
    - port: 6379
  selector:
    app: news_feed_data_access_redis
  type: ClusterIP