apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: token-dispenser-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: token_dispenser_redis
    spec:
      containers:
        - name: tokendispenserredis
          image: redis:alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "512Mi"
