apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: token-dispenser
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: token_dispenser
    spec:
      containers:
        - name: tokendispenser
          image: mattpaletta/foobar-social_token_dispenser:latest
          imagePullPolicy: Always
          tty: True
          ports:
            - containerPort: 6969
          resources:
            requests:
              cpu: "500m"
              memory: "64Mi"
            limits:
              cpu: "800m"
              memory: "128Mi"
