//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: posts.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

internal protocol Foobar_Posts_Postsget_postCall: ClientCallServerStreaming {
  /// Do not call this directly, call `receive()` in the protocol extension below instead.
  func _receive(timeout: DispatchTime) throws -> Foobar_Posts_Post?
  /// Call this to wait for a result. Nonblocking.
  func receive(completion: @escaping (ResultOrRPCError<Foobar_Posts_Post?>) -> Void) throws
}

internal extension Foobar_Posts_Postsget_postCall {
  /// Call this to wait for a result. Blocking.
  func receive(timeout: DispatchTime = .distantFuture) throws -> Foobar_Posts_Post? { return try self._receive(timeout: timeout) }
}

fileprivate final class Foobar_Posts_Postsget_postCallBase: ClientCallServerStreamingBase<Foobar_Posts_Post, Foobar_Posts_Post>, Foobar_Posts_Postsget_postCall {
  override class var method: String { return "/foobar.posts.Posts/get_post" }
}

internal protocol Foobar_Posts_Postscreate_postCall: ClientCallUnary {}

fileprivate final class Foobar_Posts_Postscreate_postCallBase: ClientCallUnaryBase<Foobar_Posts_Post, Foobar_Posts_Post>, Foobar_Posts_Postscreate_postCall {
  override class var method: String { return "/foobar.posts.Posts/create_post" }
}


/// Instantiate Foobar_Posts_PostsServiceClient, then call methods of this protocol to make API calls.
internal protocol Foobar_Posts_PostsService: ServiceClient {
  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  func get_post(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Foobar_Posts_Postsget_postCall

  /// Synchronous. Unary.
  func create_post(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata) throws -> Foobar_Posts_Post
  /// Asynchronous. Unary.
  @discardableResult
  func create_post(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata, completion: @escaping (Foobar_Posts_Post?, CallResult) -> Void) throws -> Foobar_Posts_Postscreate_postCall

}

internal extension Foobar_Posts_PostsService {
  /// Asynchronous. Server-streaming.
  func get_post(_ request: Foobar_Posts_Post, completion: ((CallResult) -> Void)?) throws -> Foobar_Posts_Postsget_postCall {
    return try self.get_post(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func create_post(_ request: Foobar_Posts_Post) throws -> Foobar_Posts_Post {
    return try self.create_post(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func create_post(_ request: Foobar_Posts_Post, completion: @escaping (Foobar_Posts_Post?, CallResult) -> Void) throws -> Foobar_Posts_Postscreate_postCall {
    return try self.create_post(request, metadata: self.metadata, completion: completion)
  }

}

internal final class Foobar_Posts_PostsServiceClient: ServiceClientBase, Foobar_Posts_PostsService {
  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  internal func get_post(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Foobar_Posts_Postsget_postCall {
    return try Foobar_Posts_Postsget_postCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func create_post(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata) throws -> Foobar_Posts_Post {
    return try Foobar_Posts_Postscreate_postCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func create_post(_ request: Foobar_Posts_Post, metadata customMetadata: Metadata, completion: @escaping (Foobar_Posts_Post?, CallResult) -> Void) throws -> Foobar_Posts_Postscreate_postCall {
    return try Foobar_Posts_Postscreate_postCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
internal protocol Foobar_Posts_PostsProvider: ServiceProvider {
  func get_post(request: Foobar_Posts_Post, session: Foobar_Posts_Postsget_postSession) throws -> ServerStatus?
  func create_post(request: Foobar_Posts_Post, session: Foobar_Posts_Postscreate_postSession) throws -> Foobar_Posts_Post
}

extension Foobar_Posts_PostsProvider {
  internal var serviceName: String { return "foobar.posts.Posts" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  internal func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/foobar.posts.Posts/get_post":
      return try Foobar_Posts_Postsget_postSessionBase(
        handler: handler,
        providerBlock: { try self.get_post(request: $0, session: $1 as! Foobar_Posts_Postsget_postSessionBase) })
          .run()
    case "/foobar.posts.Posts/create_post":
      return try Foobar_Posts_Postscreate_postSessionBase(
        handler: handler,
        providerBlock: { try self.create_post(request: $0, session: $1 as! Foobar_Posts_Postscreate_postSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

internal protocol Foobar_Posts_Postsget_postSession: ServerSessionServerStreaming {
  /// Send a message to the stream. Nonblocking.
  func send(_ message: Foobar_Posts_Post, completion: @escaping (Error?) -> Void) throws
  /// Do not call this directly, call `send()` in the protocol extension below instead.
  func _send(_ message: Foobar_Posts_Post, timeout: DispatchTime) throws

  /// Close the connection and send the status. Non-blocking.
  /// This method should be called if and only if your request handler returns a nil value instead of a server status;
  /// otherwise SwiftGRPC will take care of sending the status for you.
  func close(withStatus status: ServerStatus, completion: (() -> Void)?) throws
}

internal extension Foobar_Posts_Postsget_postSession {
  /// Send a message to the stream and wait for the send operation to finish. Blocking.
  func send(_ message: Foobar_Posts_Post, timeout: DispatchTime = .distantFuture) throws { try self._send(message, timeout: timeout) }
}

fileprivate final class Foobar_Posts_Postsget_postSessionBase: ServerSessionServerStreamingBase<Foobar_Posts_Post, Foobar_Posts_Post>, Foobar_Posts_Postsget_postSession {}

internal protocol Foobar_Posts_Postscreate_postSession: ServerSessionUnary {}

fileprivate final class Foobar_Posts_Postscreate_postSessionBase: ServerSessionUnaryBase<Foobar_Posts_Post, Foobar_Posts_Post>, Foobar_Posts_Postscreate_postSession {}

